# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-14 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slyurl',
            old_name='url',
            new_name='longUrl',
        ),
        migrations.RenameField(
            model_name='slyurl',
            old_name='short_code',
            new_name='shortCode',
        ),
        migrations.AlterField(
            model_name='slyurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
