# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-16 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0002_auto_20190614_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slyurl',
            name='longUrl',
            field=models.URLField(max_length=300),
        ),
    ]
