# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-23 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0003_auto_20190616_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slyurl',
            name='shortCode',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
