# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-23 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0004_auto_20190623_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slyurl',
            name='shortCode',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
