# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-25 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shrink', '0006_auto_20190623_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='slyurl',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slyurls', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
