# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0008_auto_20190626_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slyurl',
            old_name='longUrl',
            new_name='long_url',
        ),
        migrations.RenameField(
            model_name='slyurl',
            old_name='shortCode',
            new_name='short_code',
        ),
    ]
