# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0009_auto_20190630_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='slyurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
