# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-14 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0010_slyurl_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slyurl',
            options={'ordering': ['-timestamp']},
        ),
    ]
